export const constants = {
  DATE_FORMAT: 'yyyy-MM-DD',
  DATE_TIME_FORMAT: 'yyyy-MM-DD HH:mm:ssZ',
  SHORT_DATE_FORMAT: 'MMM D',
  TIME_FORMAT_LESSON: 'h:mm A',
  DATE_FORMAT_LESSON: 'dddd, MMM DD',
  DAYS_OF_WEEK: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
  READ_ONLY_TRANSACTION: 'SET TRANSACTION READ ONLY',
  WEEKS_PER_MONTH: 4,
  STUDENT_MAX_QUIZZES_SETS: 4,
  MENTOR_MAX_QUIZZES_SETS: 4,
  STUDENT_WEEKS_TRAINING: 13,
  MENTOR_WEEKS_TRAINING: 4,
  TRAINING_COMPLETED_ID: 'trainingCompletedId',
  AVAILABLE_MENTORS_RESULTS_PER_PAGE: 5
};